package com.aemake.brontoplayer.ui.theme

import androidx.compose.ui.graphics.Color

// Bronto brand: a warm "parchment & leather" palette — terracotta/amber primaries,
// mocha secondaries, gold tertiaries, on cream (light) and warm espresso (dark).

internal val md_light_primary = Color(0xFF8F4C26)
internal val md_light_onPrimary = Color(0xFFFFFFFF)
internal val md_light_primaryContainer = Color(0xFFFFDBC8)
internal val md_light_onPrimaryContainer = Color(0xFF341100)
internal val md_light_secondary = Color(0xFF765848)
internal val md_light_onSecondary = Color(0xFFFFFFFF)
internal val md_light_secondaryContainer = Color(0xFFFCDCC9)
internal val md_light_onSecondaryContainer = Color(0xFF2C160A)
internal val md_light_tertiary = Color(0xFF6B5D2F)
internal val md_light_onTertiary = Color(0xFFFFFFFF)
internal val md_light_tertiaryContainer = Color(0xFFF5E1A7)
internal val md_light_onTertiaryContainer = Color(0xFF221B00)
internal val md_light_background = Color(0xFFFFF8F4)
internal val md_light_onBackground = Color(0xFF221A15)
internal val md_light_surface = Color(0xFFFFF8F4)
internal val md_light_onSurface = Color(0xFF221A15)
internal val md_light_surfaceVariant = Color(0xFFF3DFD1)
internal val md_light_onSurfaceVariant = Color(0xFF52443A)
internal val md_light_surfaceContainer = Color(0xFFFAEDE3)
internal val md_light_outline = Color(0xFF847469)
internal val md_light_outlineVariant = Color(0xFFD7C3B6)
internal val md_light_error = Color(0xFFBA1A1A)
internal val md_light_onError = Color(0xFFFFFFFF)

internal val md_dark_primary = Color(0xFFFFB68B)
internal val md_dark_onPrimary = Color(0xFF522300)
internal val md_dark_primaryContainer = Color(0xFF6F3611)
internal val md_dark_onPrimaryContainer = Color(0xFFFFDBC8)
internal val md_dark_secondary = Color(0xFFE6BFA9)
internal val md_dark_onSecondary = Color(0xFF432B1C)
internal val md_dark_secondaryContainer = Color(0xFF5C4131)
internal val md_dark_onSecondaryContainer = Color(0xFFFCDCC9)
internal val md_dark_tertiary = Color(0xFFD8C68D)
internal val md_dark_onTertiary = Color(0xFF3A2F05)
internal val md_dark_tertiaryContainer = Color(0xFF52461A)
internal val md_dark_onTertiaryContainer = Color(0xFFF5E1A7)
internal val md_dark_background = Color(0xFF1A120C)
internal val md_dark_onBackground = Color(0xFFF0E0D6)
internal val md_dark_surface = Color(0xFF1A120C)
internal val md_dark_onSurface = Color(0xFFF0E0D6)
internal val md_dark_surfaceVariant = Color(0xFF52443A)
internal val md_dark_onSurfaceVariant = Color(0xFFD7C3B5)
internal val md_dark_surfaceContainer = Color(0xFF271C15)
internal val md_dark_outline = Color(0xFF9F8D81)
internal val md_dark_outlineVariant = Color(0xFF52443A)
internal val md_dark_error = Color(0xFFFFB4AB)
internal val md_dark_onError = Color(0xFF690005)
